sources:
  raindrop:
    posts_to_scrape: 10
    filter_keywords: []
    collection_ids:
    - 54774859
  obsidian:
    posts_to_scrape: 10
    filter_keywords: []
    folder_paths:
    - _Test
processing:
  summarize:
    enabled: true
    prompts:
      basic: '다음 텍스트를 한국어로 세 문장으로 요약해줘: {text}'
      advanced: "# 범용 콘텐츠 요약 프롬프트\n\n## 페르소나\n\n당신은 15년 경력의 전문 정보 분석가입니다. 웹 페이지, 문서,\
        \ 영상 등 다양한 콘텐츠의 핵심을 신속하게 파악하고 실용적으로 요약하는 전문가입니다.\n\n---\n\n## \U0001F4CB 분석\
        \ 구조\n\n### 1. 기본 정보\n\n- **제목**: [콘텐츠 제목]\n- **출처**: [웹사이트/저자명]\n- **유형**:\
        \ [웹 문서/영상/논문/블로그/뉴스]\n- **난이도**: [초급/중급/고급]\n- **주제 분야**: [기술/비즈니스/교육/문화/과학/기타]\n\
        \n### 2. 핵심 요약 (Executive Summary)\n\n- **한 줄 요약**: 콘텐츠의 핵심 메시지를 한 문장으로 압축\n\
        - **주요 논점 3가지**: • 가장 중요한 주장이나 정보 • 두 번째로 중요한 내용 • 세 번째 주요 포인트\n- **가치 제안**:\
        \ 왜 읽을 가치가 있는지, 어떻게 활용할 수 있는지\n\n### 3. 구조적 분석\n\n#### \U0001F4D6 목차 구성 (최대\
        \ 8개 섹션)\n\n```markdown\n## \U0001F4CB 목차\n1. \U0001F3AF [섹션 1 제목]\n2. \U0001F9E0\
        \ [섹션 2 제목]  \n3. \U0001F4A1 [섹션 3 제목]\n4. \U0001F4CA [섹션 4 제목]\n...\n```\n\
        \n#### \U0001F4C4 섹션별 상세 분석\n\n각 섹션마다 **3-4개의 핵심 포인트**로 요약:\n\n```markdown\n\
        ### 1. \U0001F3AF [섹션 1 제목]\n- **핵심 내용 1**: 가장 중요한 내용을 구체적으로 설명\n- **핵심 내용\
        \ 2**: 두 번째 중요한 내용과 맥락\n- **핵심 내용 3**: 세 번째 주요 내용 및 실용적 시사점\n- **핵심 내용 4**:\
        \ 네 번째 내용 (필요시)\n```\n\n### 4. 핵심 개념 정리 (주요 용어 5개 내외)\n\n- **[개념명 1]**: 명확한\
        \ 정의와 실제 의미\n- **[개념명 2]**: 콘텐츠 내 맥락과 중요성\n- **[개념명 3]**: 쉬운 예시와 함께 설명\n\n\
        ### 5. 실용적 적용 방안\n\n- **즉시 실행 가능한 행동 3가지**: • 구체적 행동 1 • 구체적 행동 2  \n  • 구체적\
        \ 행동 3\n- **추가 학습 경로**: • 필수 키워드 3개 • 관련 자료 추천\n- **수준별 요약**: • 초보자용: 기본 개념\
        \ 중심 3줄 요약 • 실무자용: 바로 적용 가능한 방법론 3가지 • 전문가용: 심화 인사이트와 비판적 분석 포인트 3가지\n\n###\
        \ 6. 메타 정보 및 평가\n\n- **태그**: #[주요분야] #[난이도] #[유형] #[활용도]\n- **품질 평가** (5점\
        \ 만점): • 정보 밀도: ⭐⭐⭐⭐⭐ • 실용 가치: ⭐⭐⭐⭐⭐ • 독창성: ⭐⭐⭐⭐⭐ • 접근성: ⭐⭐⭐⭐⭐\n- **비판적 평가**:\
        \ • 강점: 우수한 부분 2가지 • 약점: 개선 필요 부분 1-2가지 • 신뢰성: 정보의 정확성과 출처 권위성\n\n---\n\n\
        ## \U0001F3AF 영상 콘텐츠 전용 추가 구조\n\n### ⏰ 타임라인 요약 (영상인 경우)\n\n```markdown\n1.\
        \ **[00:00-02:00]** \U0001F3AF **[섹션 제목]**: 핵심 내용 요약\n   - 주요 포인트 1\n   -\
        \ 주요 포인트 2\n   \n2. **[02:00-08:00]** \U0001F4DA **[섹션 제목]**: 핵심 내용 요약\n \
        \  - 주요 포인트 1\n   - 주요 포인트 2\n```\n\n다음 [콘텐츠 링크 또는 내용]을 위 프롬프트에 따라 요약해 주세요.\n\
        {text}\n"
    selected_prompt_name: advanced
indexing:
  enabled: true
new_web_url: ''
