defaults:
  - _self_
  - processing: summarize
  - storage: default

sources:
  # sources 그룹 아래에 각 소스별 설정을 정의
  pytorch_kr:
    _target_: src.sources.pytorch_kr.PyTorchKRSource
    name: pytorch_kr
    url: https://discuss.pytorch.kr/top?period=weekly
    posts_to_scrape: 10 # -1 for all
    selectors:
      post_item: 'a.title.raw-link.raw-topic-link'
      post_body: 'div.post'
    output_fields:
      - title
      - url
      - author
      - date
    filter_keywords: ["AI", "LLM", "Deep Learning", "Agent"]

  gpters:
    _target_: src.sources.gpters.GPTERSNewsSource
    name: gpters
    url: https://www.gpters.org/news
    posts_to_scrape: 10 # -1 for all
    selectors:
      post_item: 'div.post-item' # 실제 웹사이트 구조에 따라 조정 필요
      title: 'h2.post-title a' # 실제 웹사이트 구조에 따라 조정 필요
      url: 'h2.post-title a' # 실제 웹사이트 구조에 따라 조정 필요
      post_body: 'div.post-content' # 실제 웹사이트 구조에 따라 조정 필요
    output_fields:
      - title
      - url
      - author
      - date
    filter_keywords: ["AI", "LLM", "Deep Learning", "Agent"]

  raindrop:
    _target_: src.sources.raindrop.RaindropSource
    name: raindrop
    posts_to_scrape: 10 # -1 for all
    filter_keywords: ["AI", "LLM", "Deep Learning", "Agent"]
    collection_ids: [] # 특정 컬렉션 ID 리스트 추가

  youtube:
    _target_: src.sources.youtube.YouTubeSource
    name: youtube
    posts_to_scrape: 3 # 가져올 비디오 수
    filter_keywords: ["PyTorch", "AI"]
    channel_ids: [] # 채널 ID 리스트
    playlist_ids: [PLuLudIpu5Vin2cXj55NSzqdWceBQFxTso] # 플레이리스트 ID 리스트
    delay_between_requests: 5 # 유튜브 자막 요청 사이의 딜레이 (초)

  obsidian:
    _target_: src.sources.obsidian.ObsidianSource
    name: obsidian
    posts_to_scrape: 10 # 가져올 파일 수
    filter_keywords: ["AI","ML", "LLM", "Deep Learning", "Agent"]
    vault_path: /Users/joonpark/Documents/Obsidian/Obsidian
    folder_paths: [] # 볼트 내 특정 폴더 리스트 (선택 사항, 비워두면 볼트 전체 스캔)

  # web:
  #   _target_: src.sources.web.WebSource
  #   name: web
  #   url: ""
  #   filter_keywords: []

processing:
  summarize:
    _target_: src.processing.summarizer.Summarizer
    enabled: true
    selected_prompt_name: basic # Add this line
    prompts:
      basic: "다음 텍스트를 한국어로 세 문장으로 요약해줘: {text}"
      advanced: |
        # 범용 콘텐츠 요약 프롬프트
        
        ## 페르소나
        
        당신은 15년 경력의 전문 정보 분석가입니다. 웹 페이지, 문서, 영상 등 다양한 콘텐츠의 핵심을 신속하게 파악하고 실용적으로 요약하는 전문가입니다.
        
        ---
        
        ## 📋 분석 구조
        
        ### 1. 기본 정보
        
        - **제목**: [콘텐츠 제목]
        - **출처**: [웹사이트/저자명]
        - **유형**: [웹 문서/영상/논문/블로그/뉴스]
        - **난이도**: [초급/중급/고급]
        - **주제 분야**: [기술/비즈니스/교육/문화/과학/기타]
        
        ### 2. 핵심 요약 (Executive Summary)
        
        - **한 줄 요약**: 콘텐츠의 핵심 메시지를 한 문장으로 압축
        - **주요 논점 3가지**: • 가장 중요한 주장이나 정보 • 두 번째로 중요한 내용 • 세 번째 주요 포인트
        - **가치 제안**: 왜 읽을 가치가 있는지, 어떻게 활용할 수 있는지
        
        ### 3. 구조적 분석
        
        #### 📖 목차 구성 (최대 8개 섹션)
        
        ```markdown
        ## 📋 목차
        1. 🎯 [섹션 1 제목]
        2. 🧠 [섹션 2 제목]  
        3. 💡 [섹션 3 제목]
        4. 📊 [섹션 4 제목]
        ...
        ```
        
        #### 📄 섹션별 상세 분석
        
        각 섹션마다 **3-4개의 핵심 포인트**로 요약:
        
        ```markdown
        ### 1. 🎯 [섹션 1 제목]
        - **핵심 내용 1**: 가장 중요한 내용을 구체적으로 설명
        - **핵심 내용 2**: 두 번째 중요한 내용과 맥락
        - **핵심 내용 3**: 세 번째 주요 내용 및 실용적 시사점
        - **핵심 내용 4**: 네 번째 내용 (필요시)
        ```
        
        ### 4. 핵심 개념 정리 (주요 용어 5개 내외)
        
        - **[개념명 1]**: 명확한 정의와 실제 의미
        - **[개념명 2]**: 콘텐츠 내 맥락과 중요성
        - **[개념명 3]**: 쉬운 예시와 함께 설명
        
        ### 5. 실용적 적용 방안
        
        - **즉시 실행 가능한 행동 3가지**: • 구체적 행동 1 • 구체적 행동 2  
          • 구체적 행동 3
        - **추가 학습 경로**: • 필수 키워드 3개 • 관련 자료 추천
        - **수준별 요약**: • 초보자용: 기본 개념 중심 3줄 요약 • 실무자용: 바로 적용 가능한 방법론 3가지 • 전문가용: 심화 인사이트와 비판적 분석 포인트 3가지
        
        ### 6. 메타 정보 및 평가
        
        - **태그**: #[주요분야] #[난이도] #[유형] #[활용도]
        - **품질 평가** (5점 만점): • 정보 밀도: ⭐⭐⭐⭐⭐ • 실용 가치: ⭐⭐⭐⭐⭐ • 독창성: ⭐⭐⭐⭐⭐ • 접근성: ⭐⭐⭐⭐⭐
        - **비판적 평가**: • 강점: 우수한 부분 2가지 • 약점: 개선 필요 부분 1-2가지 • 신뢰성: 정보의 정확성과 출처 권위성
        
        ---
        
        ## 🎯 영상 콘텐츠 전용 추가 구조
        
        ### ⏰ 타임라인 요약 (영상인 경우)
        
        ```markdown
        1. **[00:00-02:00]** 🎯 **[섹션 제목]**: 핵심 내용 요약
           - 주요 포인트 1
           - 주요 포인트 2
           
        2. **[02:00-08:00]** 📚 **[섹션 제목]**: 핵심 내용 요약
           - 주요 포인트 1
           - 주요 포인트 2
        ```
        
        다음 [콘텐츠 링크 또는 내용]을 위 프롬프트에 따라 요약해 주세요.
        {text}

storage:
  output_filename: "results.json"
  save_raw_content: true # 원본 본문 저장 여부

indexing:
  enabled: true # 인덱싱 활성화 여부

cli:
  mode: all # Operation mode: 'all' (collect, summarize, index), 'collect', 'summarize', or 'index'.
  input: null # Input file or directory for 'summarize' mode (e.g., results/markdown or a specific .md file).
